/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedMonitorRouteImport } from './routes/_authenticated/monitor'
import { Route as AuthenticatedMenusRouteImport } from './routes/_authenticated/menus'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedBiddingRouteImport } from './routes/_authenticated/bidding'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AuthenticatedPriceTrendRouteImport } from './routes/_authenticated/price/trend'
import { Route as AuthenticatedPriceCompareRouteImport } from './routes/_authenticated/price/compare'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitorRoute = AuthenticatedMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenusRoute = AuthenticatedMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBiddingRoute = AuthenticatedBiddingRouteImport.update({
  id: '/bidding',
  path: '/bidding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPriceTrendRoute = AuthenticatedPriceTrendRouteImport.update({
  id: '/price/trend',
  path: '/price/trend',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPriceCompareRoute =
  AuthenticatedPriceCompareRouteImport.update({
    id: '/price/compare',
    path: '/price/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof SignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/bidding': typeof AuthenticatedBiddingRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/menus': typeof AuthenticatedMenusRoute
  '/monitor': typeof AuthenticatedMonitorRoute
  '/users': typeof AuthenticatedUsersRoute
  '/price/compare': typeof AuthenticatedPriceCompareRoute
  '/price/trend': typeof AuthenticatedPriceTrendRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/bidding': typeof AuthenticatedBiddingRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/menus': typeof AuthenticatedMenusRoute
  '/monitor': typeof AuthenticatedMonitorRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/price/compare': typeof AuthenticatedPriceCompareRoute
  '/price/trend': typeof AuthenticatedPriceTrendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/bidding': typeof AuthenticatedBiddingRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/menus': typeof AuthenticatedMenusRoute
  '/_authenticated/monitor': typeof AuthenticatedMonitorRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/price/compare': typeof AuthenticatedPriceCompareRoute
  '/_authenticated/price/trend': typeof AuthenticatedPriceTrendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/bidding'
    | '/departments'
    | '/menus'
    | '/monitor'
    | '/users'
    | '/price/compare'
    | '/price/trend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/bidding'
    | '/departments'
    | '/menus'
    | '/monitor'
    | '/users'
    | '/'
    | '/price/compare'
    | '/price/trend'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/bidding'
    | '/_authenticated/departments'
    | '/_authenticated/menus'
    | '/_authenticated/monitor'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/price/compare'
    | '/_authenticated/price/trend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor': {
      id: '/_authenticated/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AuthenticatedMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menus': {
      id: '/_authenticated/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AuthenticatedMenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bidding': {
      id: '/_authenticated/bidding'
      path: '/bidding'
      fullPath: '/bidding'
      preLoaderRoute: typeof AuthenticatedBiddingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/price/trend': {
      id: '/_authenticated/price/trend'
      path: '/price/trend'
      fullPath: '/price/trend'
      preLoaderRoute: typeof AuthenticatedPriceTrendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/price/compare': {
      id: '/_authenticated/price/compare'
      path: '/price/compare'
      fullPath: '/price/compare'
      preLoaderRoute: typeof AuthenticatedPriceCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBiddingRoute: typeof AuthenticatedBiddingRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedMenusRoute: typeof AuthenticatedMenusRoute
  AuthenticatedMonitorRoute: typeof AuthenticatedMonitorRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPriceCompareRoute: typeof AuthenticatedPriceCompareRoute
  AuthenticatedPriceTrendRoute: typeof AuthenticatedPriceTrendRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBiddingRoute: AuthenticatedBiddingRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedMenusRoute: AuthenticatedMenusRoute,
  AuthenticatedMonitorRoute: AuthenticatedMonitorRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPriceCompareRoute: AuthenticatedPriceCompareRoute,
  AuthenticatedPriceTrendRoute: AuthenticatedPriceTrendRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
